/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *action;
    QAction *action_2;
    QAction *action_3;
    QAction *action_4;
    QAction *action_5;
    QAction *action_6;
    QAction *action_achievements;
    QAction *action_7;
    QAction *action_8;
    QAction *action_9;
    QAction *action_10;
    QAction *action_live;
    QWidget *centralwidget;
    QLabel *labelPlanetName;
    QPushButton *btnCreate;
    QPushButton *btnRecreate;
    QTabWidget *tabWidget;
    QWidget *tab;
    QLabel *label;
    QSlider *sliderWorldSize;
    QLabel *label_3;
    QSlider *sliderRandomness;
    QLabel *label_5;
    QSlider *sliderTemperature;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QLabel *label_2;
    QLabel *label_4;
    QLabel *label_6;
    QLabel *label_10;
    QComboBox *comboTerraMode;
    QLabel *label_44;
    QLabel *label_45;
    QSlider *sliderIterations;
    QLabel *label_46;
    QWidget *tab_2;
    QLabel *label_11;
    QWidget *tab_3;
    QLabel *label_8;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_14;
    QPushButton *btnColorIce;
    QPushButton *btnColorRock;
    QPushButton *btnColorMountain;
    QPushButton *btnColorPlain;
    QPushButton *btnColorBeach;
    QPushButton *btnColorShallow;
    QPushButton *btnColorOcean;
    QLabel *label_12;
    QSlider *sliderNoise;
    QLabel *label_47;
    QLabel *label_48;
    QCheckBox *checkGradient;
    QWidget *tab_4;
    QCheckBox *checkPlant;
    QLabel *label_32;
    QWidget *tab_5;
    QLabel *label_13;
    QSlider *sliderShine;
    QLabel *label_22;
    QLabel *label_39;
    QWidget *tab_6;
    QLabel *label_23;
    QRadioButton *radioName1;
    QRadioButton *radioName2;
    QRadioButton *radioName3;
    QLabel *label_40;
    QWidget *tab_7;
    QCheckBox *checkCloud;
    QLabel *label_24;
    QSlider *sliderCloudSize;
    QLabel *label_26;
    QSlider *sliderCloudQuality;
    QLabel *label_28;
    QSlider *sliderCloudTransparent;
    QCheckBox *checkCorrection;
    QPushButton *btnColorCloud;
    QLabel *label_30;
    QLabel *label_27;
    QLabel *label_29;
    QLabel *label_41;
    QWidget *tab_8;
    QCheckBox *checkAtmo;
    QLabel *label_25;
    QSlider *sliderAtmoTransparent;
    QLabel *label_33;
    QSlider *sliderAtmoSize;
    QPushButton *btnColorAtmo;
    QLabel *label_35;
    QLabel *label_34;
    QLabel *label_43;
    QWidget *tab_9;
    QCheckBox *checkRing;
    QLabel *label_31;
    QSlider *sliderRingInner;
    QLabel *label_36;
    QSlider *sliderRingOuter;
    QPushButton *btnColorRing;
    QLabel *label_38;
    QLabel *label_37;
    QLabel *label_42;
    QWidget *tab_10;
    QLabel *label_9;
    QPushButton *pushButton_2;
    QFrame *line_3;
    QPushButton *btnViewPlanet;
    QPushButton *btnViewDescription;
    QPushButton *btnViewSystem;
    QPushButton *btnViewMap;
    QPushButton *btnAutogen;
    QFrame *line;
    QFrame *line_4;
    QPushButton *btnLogo;
    QMenuBar *menubar;
    QMenu *menu;
    QMenu *menu_2;
    QMenu *menuGenerationSettings;
    QMenu *menuProgramSettings;
    QMenu *menu_3;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1500, 635);
        QFont font;
        font.setPointSize(27);
        MainWindow->setFont(font);
        MainWindow->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        action = new QAction(MainWindow);
        action->setObjectName(QString::fromUtf8("action"));
        action_2 = new QAction(MainWindow);
        action_2->setObjectName(QString::fromUtf8("action_2"));
        action_3 = new QAction(MainWindow);
        action_3->setObjectName(QString::fromUtf8("action_3"));
        action_4 = new QAction(MainWindow);
        action_4->setObjectName(QString::fromUtf8("action_4"));
        action_5 = new QAction(MainWindow);
        action_5->setObjectName(QString::fromUtf8("action_5"));
        action_6 = new QAction(MainWindow);
        action_6->setObjectName(QString::fromUtf8("action_6"));
        action_achievements = new QAction(MainWindow);
        action_achievements->setObjectName(QString::fromUtf8("action_achievements"));
        action_7 = new QAction(MainWindow);
        action_7->setObjectName(QString::fromUtf8("action_7"));
        action_8 = new QAction(MainWindow);
        action_8->setObjectName(QString::fromUtf8("action_8"));
        action_9 = new QAction(MainWindow);
        action_9->setObjectName(QString::fromUtf8("action_9"));
        action_10 = new QAction(MainWindow);
        action_10->setObjectName(QString::fromUtf8("action_10"));
        action_live = new QAction(MainWindow);
        action_live->setObjectName(QString::fromUtf8("action_live"));
        action_live->setCheckable(true);
        action_live->setChecked(false);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        labelPlanetName = new QLabel(centralwidget);
        labelPlanetName->setObjectName(QString::fromUtf8("labelPlanetName"));
        labelPlanetName->setGeometry(QRect(510, 0, 421, 71));
        QPalette palette;
        QBrush brush(QColor(110, 170, 200, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(0, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        QBrush brush2(QColor(120, 120, 120, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        labelPlanetName->setPalette(palette);
        QFont font1;
        font1.setFamily(QString::fromUtf8("Consolas"));
        font1.setPointSize(24);
        labelPlanetName->setFont(font1);
        labelPlanetName->setText(QString::fromUtf8("..."));
        labelPlanetName->setAlignment(Qt::AlignCenter);
        btnCreate = new QPushButton(centralwidget);
        btnCreate->setObjectName(QString::fromUtf8("btnCreate"));
        btnCreate->setGeometry(QRect(1000, 0, 480, 72));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        btnCreate->setPalette(palette1);
        btnCreate->setFont(font1);
        btnCreate->setStyleSheet(QString::fromUtf8(""));
        btnRecreate = new QPushButton(centralwidget);
        btnRecreate->setObjectName(QString::fromUtf8("btnRecreate"));
        btnRecreate->setGeometry(QRect(1000, 80, 480, 72));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        btnRecreate->setPalette(palette2);
        btnRecreate->setFont(font1);
        btnRecreate->setStyleSheet(QString::fromUtf8(""));
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(10, 0, 491, 571));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        tabWidget->setPalette(palette3);
        QFont font2;
        font2.setKerning(true);
        tabWidget->setFont(font2);
        tabWidget->setAutoFillBackground(false);
        tabWidget->setStyleSheet(QString::fromUtf8(""));
        tabWidget->setTabPosition(QTabWidget::West);
        tabWidget->setIconSize(QSize(15, 16));
        tabWidget->setElideMode(Qt::ElideNone);
        tabWidget->setUsesScrollButtons(true);
        tabWidget->setDocumentMode(false);
        tabWidget->setTabBarAutoHide(false);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        label = new QLabel(tab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 230, 171, 31));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label->setPalette(palette4);
        QFont font3;
        font3.setFamily(QString::fromUtf8("Consolas"));
        font3.setPointSize(10);
        label->setFont(font3);
        sliderWorldSize = new QSlider(tab);
        sliderWorldSize->setObjectName(QString::fromUtf8("sliderWorldSize"));
        sliderWorldSize->setGeometry(QRect(20, 270, 221, 16));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush1);
        QBrush brush3(QColor(0, 255, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        QBrush brush4(QColor(0, 120, 215, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Disabled, QPalette::Highlight, brush4);
        sliderWorldSize->setPalette(palette5);
        QFont font4;
        font4.setPointSize(14);
        sliderWorldSize->setFont(font4);
        sliderWorldSize->setStyleSheet(QString::fromUtf8("QSlider::handle:horizontal {background-color: rgb(0,255,127);}\n"
"QSlider::handle:horizontal {selection-background-color: rgb(0, 255, 0);}"));
        sliderWorldSize->setMinimum(1);
        sliderWorldSize->setMaximum(20);
        sliderWorldSize->setOrientation(Qt::Horizontal);
        sliderWorldSize->setInvertedAppearance(false);
        sliderWorldSize->setInvertedControls(false);
        sliderWorldSize->setTickPosition(QSlider::NoTicks);
        label_3 = new QLabel(tab);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setEnabled(true);
        label_3->setGeometry(QRect(20, 110, 171, 31));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_3->setPalette(palette6);
        label_3->setFont(font3);
        sliderRandomness = new QSlider(tab);
        sliderRandomness->setObjectName(QString::fromUtf8("sliderRandomness"));
        sliderRandomness->setGeometry(QRect(20, 150, 221, 16));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Highlight, brush4);
        sliderRandomness->setPalette(palette7);
        sliderRandomness->setMinimum(1);
        sliderRandomness->setMaximum(10);
        sliderRandomness->setOrientation(Qt::Horizontal);
        sliderRandomness->setInvertedAppearance(false);
        sliderRandomness->setInvertedControls(false);
        label_5 = new QLabel(tab);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(20, 290, 171, 31));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_5->setPalette(palette8);
        label_5->setFont(font3);
        sliderTemperature = new QSlider(tab);
        sliderTemperature->setObjectName(QString::fromUtf8("sliderTemperature"));
        sliderTemperature->setGeometry(QRect(20, 330, 221, 16));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Highlight, brush4);
        sliderTemperature->setPalette(palette9);
        sliderTemperature->setStyleSheet(QString::fromUtf8("QSlider::handle:horizontal {background-color: rgb(0,255,0);\n"
"border-radius: 7px;border-color: rgb(0, 255, 127);}\n"
"QSlider::add-page:horizontal  {background: rgb(0,255,127);margin: 5px;\n"
"margin-right: 0px;}\n"
"QSlider::sub-page:horizontal {background: rgb(0,255,0);\n"
"margin: 5px;}"));
        sliderTemperature->setMinimum(-90);
        sliderTemperature->setMaximum(140);
        sliderTemperature->setOrientation(Qt::Horizontal);
        sliderTemperature->setInvertedAppearance(false);
        sliderTemperature->setInvertedControls(false);
        pushButton_6 = new QPushButton(tab);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(320, 350, 111, 22));
        pushButton_6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        pushButton_7 = new QPushButton(tab);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(320, 380, 111, 22));
        pushButton_7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(240, 260, 41, 21));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_2->setPalette(palette10);
        QFont font5;
        font5.setPointSize(10);
        label_2->setFont(font5);
        label_2->setText(QString::fromUtf8("0"));
        label_2->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(tab);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(240, 140, 41, 21));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_4->setPalette(palette11);
        label_4->setFont(font5);
        label_4->setText(QString::fromUtf8("0"));
        label_4->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(tab);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(240, 320, 41, 21));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_6->setPalette(palette12);
        label_6->setFont(font5);
        label_6->setText(QString::fromUtf8("0"));
        label_6->setAlignment(Qt::AlignCenter);
        label_10 = new QLabel(tab);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 10, 210, 30));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Consolas"));
        font6.setPointSize(12);
        label_10->setFont(font6);
        comboTerraMode = new QComboBox(tab);
        comboTerraMode->addItem(QString());
        comboTerraMode->addItem(QString());
        comboTerraMode->setObjectName(QString::fromUtf8("comboTerraMode"));
        comboTerraMode->setGeometry(QRect(20, 80, 291, 31));
        comboTerraMode->setFont(font3);
        comboTerraMode->setStyleSheet(QString::fromUtf8(""));
        label_44 = new QLabel(tab);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setEnabled(true);
        label_44->setGeometry(QRect(20, 40, 171, 31));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_44->setPalette(palette13);
        label_44->setFont(font3);
        label_45 = new QLabel(tab);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setEnabled(true);
        label_45->setGeometry(QRect(20, 170, 171, 31));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_45->setPalette(palette14);
        label_45->setFont(font3);
        sliderIterations = new QSlider(tab);
        sliderIterations->setObjectName(QString::fromUtf8("sliderIterations"));
        sliderIterations->setGeometry(QRect(20, 210, 221, 16));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Highlight, brush4);
        sliderIterations->setPalette(palette15);
        sliderIterations->setMinimum(50);
        sliderIterations->setMaximum(1000);
        sliderIterations->setOrientation(Qt::Horizontal);
        sliderIterations->setInvertedAppearance(false);
        sliderIterations->setInvertedControls(false);
        sliderIterations->setTickPosition(QSlider::NoTicks);
        label_46 = new QLabel(tab);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(240, 200, 41, 21));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_46->setPalette(palette16);
        label_46->setFont(font5);
        label_46->setText(QString::fromUtf8("0"));
        label_46->setAlignment(Qt::AlignCenter);
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        label_11 = new QLabel(tab_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 10, 210, 30));
        QFont font7;
        font7.setFamily(QString::fromUtf8("Consolas"));
        font7.setPointSize(12);
        font7.setKerning(true);
        label_11->setFont(font7);
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        label_8 = new QLabel(tab_3);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 40, 121, 30));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_8->setPalette(palette17);
        QFont font8;
        font8.setFamily(QString::fromUtf8("Consolas"));
        label_8->setFont(font8);
        label_8->setAlignment(Qt::AlignCenter);
        label_15 = new QLabel(tab_3);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(10, 75, 121, 40));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_15->setPalette(palette18);
        label_15->setFont(font3);
        label_15->setAlignment(Qt::AlignCenter);
        label_16 = new QLabel(tab_3);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 120, 121, 40));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_16->setPalette(palette19);
        label_16->setFont(font3);
        label_16->setAlignment(Qt::AlignCenter);
        label_17 = new QLabel(tab_3);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(10, 165, 121, 40));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette20.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette20.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette20.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette20.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette20.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_17->setPalette(palette20);
        label_17->setFont(font3);
        label_17->setAlignment(Qt::AlignCenter);
        label_18 = new QLabel(tab_3);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 210, 121, 40));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette21.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette21.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette21.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette21.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette21.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_18->setPalette(palette21);
        label_18->setFont(font3);
        label_18->setAlignment(Qt::AlignCenter);
        label_19 = new QLabel(tab_3);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(10, 255, 121, 40));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette22.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_19->setPalette(palette22);
        label_19->setFont(font3);
        label_19->setAlignment(Qt::AlignCenter);
        label_20 = new QLabel(tab_3);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 300, 121, 40));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette23.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette23.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette23.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette23.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette23.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_20->setPalette(palette23);
        label_20->setFont(font3);
        label_20->setAlignment(Qt::AlignCenter);
        label_21 = new QLabel(tab_3);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 345, 121, 40));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette24.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette24.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette24.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette24.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette24.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_21->setPalette(palette24);
        label_21->setFont(font3);
        label_21->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(tab_3);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(130, 40, 151, 31));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_14->setPalette(palette25);
        label_14->setFont(font8);
        label_14->setAlignment(Qt::AlignCenter);
        btnColorIce = new QPushButton(tab_3);
        btnColorIce->setObjectName(QString::fromUtf8("btnColorIce"));
        btnColorIce->setGeometry(QRect(131, 75, 151, 40));
        btnColorIce->setStyleSheet(QString::fromUtf8("QPushButton{background-color: rgb(66,66,66);}"));
        btnColorRock = new QPushButton(tab_3);
        btnColorRock->setObjectName(QString::fromUtf8("btnColorRock"));
        btnColorRock->setGeometry(QRect(131, 120, 151, 40));
        btnColorRock->setStyleSheet(QString::fromUtf8("QPushButton{background-color: rgb(66,66,66);}"));
        btnColorMountain = new QPushButton(tab_3);
        btnColorMountain->setObjectName(QString::fromUtf8("btnColorMountain"));
        btnColorMountain->setGeometry(QRect(131, 165, 151, 40));
        btnColorMountain->setStyleSheet(QString::fromUtf8("QPushButton{background-color: rgb(66,66,66);}"));
        btnColorPlain = new QPushButton(tab_3);
        btnColorPlain->setObjectName(QString::fromUtf8("btnColorPlain"));
        btnColorPlain->setGeometry(QRect(131, 210, 151, 40));
        btnColorPlain->setStyleSheet(QString::fromUtf8("QPushButton{background-color: rgb(66,66,66);}"));
        btnColorBeach = new QPushButton(tab_3);
        btnColorBeach->setObjectName(QString::fromUtf8("btnColorBeach"));
        btnColorBeach->setGeometry(QRect(131, 255, 151, 40));
        btnColorBeach->setStyleSheet(QString::fromUtf8("QPushButton{background-color: rgb(66,66,66);}"));
        btnColorShallow = new QPushButton(tab_3);
        btnColorShallow->setObjectName(QString::fromUtf8("btnColorShallow"));
        btnColorShallow->setGeometry(QRect(131, 300, 151, 40));
        btnColorShallow->setStyleSheet(QString::fromUtf8("QPushButton{background-color: rgb(66,66,66);}"));
        btnColorOcean = new QPushButton(tab_3);
        btnColorOcean->setObjectName(QString::fromUtf8("btnColorOcean"));
        btnColorOcean->setGeometry(QRect(131, 345, 151, 40));
        btnColorOcean->setStyleSheet(QString::fromUtf8("QPushButton{background-color: rgb(66,66,66);}"));
        label_12 = new QLabel(tab_3);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 10, 210, 30));
        label_12->setFont(font7);
        sliderNoise = new QSlider(tab_3);
        sliderNoise->setObjectName(QString::fromUtf8("sliderNoise"));
        sliderNoise->setGeometry(QRect(10, 440, 221, 16));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette26.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette26.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette26.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette26.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette26.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette26.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette26.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette26.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::Highlight, brush4);
        sliderNoise->setPalette(palette26);
        sliderNoise->setMinimum(0);
        sliderNoise->setMaximum(100);
        sliderNoise->setValue(0);
        sliderNoise->setOrientation(Qt::Horizontal);
        sliderNoise->setInvertedAppearance(false);
        sliderNoise->setInvertedControls(false);
        label_47 = new QLabel(tab_3);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(10, 410, 171, 31));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette27.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette27.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette27.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette27.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette27.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_47->setPalette(palette27);
        label_47->setFont(font3);
        label_48 = new QLabel(tab_3);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(230, 430, 41, 21));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette28.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette28.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_48->setPalette(palette28);
        label_48->setFont(font3);
        label_48->setText(QString::fromUtf8("0"));
        label_48->setAlignment(Qt::AlignCenter);
        checkGradient = new QCheckBox(tab_3);
        checkGradient->setObjectName(QString::fromUtf8("checkGradient"));
        checkGradient->setGeometry(QRect(10, 460, 131, 31));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette29.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette29.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette29.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette29.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette29.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        checkGradient->setPalette(palette29);
        checkGradient->setFont(font3);
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        checkPlant = new QCheckBox(tab_4);
        checkPlant->setObjectName(QString::fromUtf8("checkPlant"));
        checkPlant->setGeometry(QRect(10, 50, 241, 20));
        QFont font9;
        font9.setFamily(QString::fromUtf8("Consolas"));
        font9.setPointSize(10);
        font9.setKerning(true);
        checkPlant->setFont(font9);
        label_32 = new QLabel(tab_4);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(10, 10, 210, 30));
        label_32->setFont(font7);
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        label_13 = new QLabel(tab_5);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 50, 171, 31));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette30.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette30.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette30.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette30.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette30.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette30.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette30.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette30.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_13->setPalette(palette30);
        label_13->setFont(font3);
        sliderShine = new QSlider(tab_5);
        sliderShine->setObjectName(QString::fromUtf8("sliderShine"));
        sliderShine->setGeometry(QRect(10, 80, 221, 16));
        sliderShine->setMinimum(0);
        sliderShine->setMaximum(5);
        sliderShine->setOrientation(Qt::Horizontal);
        sliderShine->setInvertedAppearance(false);
        sliderShine->setInvertedControls(false);
        label_22 = new QLabel(tab_5);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(230, 70, 41, 21));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette31.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette31.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette31.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette31.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette31.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette31.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette31.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette31.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_22->setPalette(palette31);
        label_22->setFont(font3);
        label_22->setText(QString::fromUtf8("0"));
        label_22->setAlignment(Qt::AlignCenter);
        label_39 = new QLabel(tab_5);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(10, 10, 210, 30));
        label_39->setFont(font7);
        tabWidget->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        label_23 = new QLabel(tab_6);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(10, 50, 191, 31));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette32.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette32.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette32.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette32.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette32.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_23->setPalette(palette32);
        label_23->setFont(font3);
        radioName1 = new QRadioButton(tab_6);
        radioName1->setObjectName(QString::fromUtf8("radioName1"));
        radioName1->setGeometry(QRect(10, 80, 261, 41));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        radioName1->setPalette(palette33);
        radioName1->setFont(font3);
        radioName2 = new QRadioButton(tab_6);
        radioName2->setObjectName(QString::fromUtf8("radioName2"));
        radioName2->setGeometry(QRect(10, 120, 261, 41));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette34.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette34.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette34.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette34.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette34.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        radioName2->setPalette(palette34);
        radioName2->setFont(font3);
        radioName3 = new QRadioButton(tab_6);
        radioName3->setObjectName(QString::fromUtf8("radioName3"));
        radioName3->setGeometry(QRect(10, 160, 261, 41));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette35.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette35.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette35.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette35.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette35.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        radioName3->setPalette(palette35);
        radioName3->setFont(font3);
        label_40 = new QLabel(tab_6);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(10, 10, 210, 30));
        label_40->setFont(font7);
        tabWidget->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        checkCloud = new QCheckBox(tab_7);
        checkCloud->setObjectName(QString::fromUtf8("checkCloud"));
        checkCloud->setGeometry(QRect(10, 50, 131, 31));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette36.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette36.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette36.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette36.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette36.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        checkCloud->setPalette(palette36);
        checkCloud->setFont(font3);
        label_24 = new QLabel(tab_7);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(10, 90, 101, 31));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette37.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette37.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette37.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette37.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette37.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_24->setPalette(palette37);
        label_24->setFont(font3);
        sliderCloudSize = new QSlider(tab_7);
        sliderCloudSize->setObjectName(QString::fromUtf8("sliderCloudSize"));
        sliderCloudSize->setGeometry(QRect(10, 130, 221, 16));
        sliderCloudSize->setMinimum(1);
        sliderCloudSize->setMaximum(10);
        sliderCloudSize->setOrientation(Qt::Horizontal);
        sliderCloudSize->setInvertedAppearance(false);
        sliderCloudSize->setInvertedControls(false);
        label_26 = new QLabel(tab_7);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(10, 150, 171, 31));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette38.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette38.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette38.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette38.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette38.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette38.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette38.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette38.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_26->setPalette(palette38);
        label_26->setFont(font3);
        sliderCloudQuality = new QSlider(tab_7);
        sliderCloudQuality->setObjectName(QString::fromUtf8("sliderCloudQuality"));
        sliderCloudQuality->setGeometry(QRect(10, 190, 221, 16));
        sliderCloudQuality->setMinimum(1);
        sliderCloudQuality->setMaximum(6);
        sliderCloudQuality->setOrientation(Qt::Horizontal);
        sliderCloudQuality->setInvertedAppearance(false);
        sliderCloudQuality->setInvertedControls(false);
        label_28 = new QLabel(tab_7);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 210, 231, 31));
        QPalette palette39;
        palette39.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette39.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette39.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette39.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette39.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette39.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette39.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette39.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette39.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_28->setPalette(palette39);
        label_28->setFont(font3);
        sliderCloudTransparent = new QSlider(tab_7);
        sliderCloudTransparent->setObjectName(QString::fromUtf8("sliderCloudTransparent"));
        sliderCloudTransparent->setGeometry(QRect(10, 240, 221, 16));
        sliderCloudTransparent->setMinimum(0);
        sliderCloudTransparent->setMaximum(10);
        sliderCloudTransparent->setValue(0);
        sliderCloudTransparent->setOrientation(Qt::Horizontal);
        sliderCloudTransparent->setInvertedAppearance(false);
        sliderCloudTransparent->setInvertedControls(false);
        checkCorrection = new QCheckBox(tab_7);
        checkCorrection->setObjectName(QString::fromUtf8("checkCorrection"));
        checkCorrection->setGeometry(QRect(10, 260, 221, 31));
        QPalette palette40;
        palette40.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette40.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette40.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette40.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette40.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette40.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette40.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette40.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette40.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        checkCorrection->setPalette(palette40);
        checkCorrection->setFont(font3);
        btnColorCloud = new QPushButton(tab_7);
        btnColorCloud->setObjectName(QString::fromUtf8("btnColorCloud"));
        btnColorCloud->setGeometry(QRect(10, 300, 141, 51));
        btnColorCloud->setFont(font3);
        btnColorCloud->setStyleSheet(QString::fromUtf8("QPushButton{background-color: rgb(66,66,66);}"));
        label_30 = new QLabel(tab_7);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(230, 120, 41, 21));
        QPalette palette41;
        palette41.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette41.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette41.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette41.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette41.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette41.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette41.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette41.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette41.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_30->setPalette(palette41);
        label_30->setFont(font3);
        label_30->setText(QString::fromUtf8("0"));
        label_30->setAlignment(Qt::AlignCenter);
        label_27 = new QLabel(tab_7);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(230, 180, 41, 21));
        QPalette palette42;
        palette42.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette42.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette42.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette42.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette42.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette42.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette42.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette42.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette42.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_27->setPalette(palette42);
        label_27->setFont(font3);
        label_27->setText(QString::fromUtf8("0"));
        label_27->setAlignment(Qt::AlignCenter);
        label_29 = new QLabel(tab_7);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(230, 230, 41, 21));
        QPalette palette43;
        palette43.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette43.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette43.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette43.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette43.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette43.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette43.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette43.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette43.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_29->setPalette(palette43);
        label_29->setFont(font3);
        label_29->setText(QString::fromUtf8("0"));
        label_29->setAlignment(Qt::AlignCenter);
        label_41 = new QLabel(tab_7);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(10, 10, 210, 30));
        label_41->setFont(font7);
        tabWidget->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QString::fromUtf8("tab_8"));
        checkAtmo = new QCheckBox(tab_8);
        checkAtmo->setObjectName(QString::fromUtf8("checkAtmo"));
        checkAtmo->setGeometry(QRect(10, 50, 221, 31));
        QPalette palette44;
        palette44.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette44.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette44.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette44.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette44.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette44.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette44.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette44.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette44.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        checkAtmo->setPalette(palette44);
        checkAtmo->setFont(font3);
        label_25 = new QLabel(tab_8);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(10, 80, 231, 31));
        QPalette palette45;
        palette45.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_25->setPalette(palette45);
        label_25->setFont(font3);
        sliderAtmoTransparent = new QSlider(tab_8);
        sliderAtmoTransparent->setObjectName(QString::fromUtf8("sliderAtmoTransparent"));
        sliderAtmoTransparent->setGeometry(QRect(10, 110, 221, 16));
        sliderAtmoTransparent->setMinimum(0);
        sliderAtmoTransparent->setMaximum(10);
        sliderAtmoTransparent->setOrientation(Qt::Horizontal);
        sliderAtmoTransparent->setInvertedAppearance(false);
        sliderAtmoTransparent->setInvertedControls(false);
        label_33 = new QLabel(tab_8);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(10, 130, 231, 31));
        QPalette palette46;
        palette46.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette46.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette46.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette46.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette46.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette46.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette46.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette46.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette46.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_33->setPalette(palette46);
        label_33->setFont(font3);
        sliderAtmoSize = new QSlider(tab_8);
        sliderAtmoSize->setObjectName(QString::fromUtf8("sliderAtmoSize"));
        sliderAtmoSize->setGeometry(QRect(10, 160, 221, 16));
        sliderAtmoSize->setMinimum(1);
        sliderAtmoSize->setMaximum(10);
        sliderAtmoSize->setOrientation(Qt::Horizontal);
        sliderAtmoSize->setInvertedAppearance(false);
        sliderAtmoSize->setInvertedControls(false);
        btnColorAtmo = new QPushButton(tab_8);
        btnColorAtmo->setObjectName(QString::fromUtf8("btnColorAtmo"));
        btnColorAtmo->setGeometry(QRect(10, 190, 141, 51));
        btnColorAtmo->setFont(font3);
        btnColorAtmo->setStyleSheet(QString::fromUtf8("QPushButton{background-color: rgb(66,66,66);}"));
        label_35 = new QLabel(tab_8);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(230, 100, 41, 21));
        QPalette palette47;
        palette47.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette47.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette47.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette47.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette47.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette47.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette47.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette47.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette47.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_35->setPalette(palette47);
        label_35->setFont(font3);
        label_35->setText(QString::fromUtf8("0"));
        label_35->setAlignment(Qt::AlignCenter);
        label_34 = new QLabel(tab_8);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(230, 150, 41, 21));
        QPalette palette48;
        palette48.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette48.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette48.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette48.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette48.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette48.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette48.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette48.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette48.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_34->setPalette(palette48);
        label_34->setFont(font3);
        label_34->setText(QString::fromUtf8("0"));
        label_34->setAlignment(Qt::AlignCenter);
        label_43 = new QLabel(tab_8);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(10, 10, 210, 30));
        label_43->setFont(font7);
        tabWidget->addTab(tab_8, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QString::fromUtf8("tab_9"));
        checkRing = new QCheckBox(tab_9);
        checkRing->setObjectName(QString::fromUtf8("checkRing"));
        checkRing->setGeometry(QRect(10, 50, 131, 31));
        QPalette palette49;
        palette49.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette49.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette49.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette49.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette49.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette49.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette49.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette49.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette49.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        checkRing->setPalette(palette49);
        checkRing->setFont(font3);
        label_31 = new QLabel(tab_9);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(10, 80, 171, 31));
        QPalette palette50;
        palette50.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette50.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette50.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette50.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette50.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette50.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette50.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette50.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette50.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_31->setPalette(palette50);
        label_31->setFont(font3);
        sliderRingInner = new QSlider(tab_9);
        sliderRingInner->setObjectName(QString::fromUtf8("sliderRingInner"));
        sliderRingInner->setGeometry(QRect(10, 110, 221, 16));
        sliderRingInner->setMinimum(1);
        sliderRingInner->setMaximum(5);
        sliderRingInner->setOrientation(Qt::Horizontal);
        sliderRingInner->setInvertedAppearance(false);
        sliderRingInner->setInvertedControls(false);
        label_36 = new QLabel(tab_9);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(10, 130, 171, 31));
        QPalette palette51;
        palette51.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette51.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette51.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette51.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette51.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette51.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette51.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette51.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette51.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_36->setPalette(palette51);
        label_36->setFont(font3);
        sliderRingOuter = new QSlider(tab_9);
        sliderRingOuter->setObjectName(QString::fromUtf8("sliderRingOuter"));
        sliderRingOuter->setGeometry(QRect(10, 160, 221, 16));
        sliderRingOuter->setMinimum(1);
        sliderRingOuter->setMaximum(5);
        sliderRingOuter->setOrientation(Qt::Horizontal);
        sliderRingOuter->setInvertedAppearance(false);
        sliderRingOuter->setInvertedControls(false);
        btnColorRing = new QPushButton(tab_9);
        btnColorRing->setObjectName(QString::fromUtf8("btnColorRing"));
        btnColorRing->setGeometry(QRect(10, 190, 141, 51));
        btnColorRing->setFont(font3);
        btnColorRing->setStyleSheet(QString::fromUtf8("QPushButton{background-color: rgb(66,66,66);}"));
        label_38 = new QLabel(tab_9);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(230, 100, 41, 21));
        QPalette palette52;
        palette52.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette52.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette52.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette52.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette52.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette52.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette52.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette52.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette52.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_38->setPalette(palette52);
        label_38->setFont(font3);
        label_38->setText(QString::fromUtf8("0"));
        label_38->setAlignment(Qt::AlignCenter);
        label_37 = new QLabel(tab_9);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(230, 150, 41, 21));
        QPalette palette53;
        palette53.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_37->setPalette(palette53);
        label_37->setFont(font3);
        label_37->setText(QString::fromUtf8("0"));
        label_37->setAlignment(Qt::AlignCenter);
        label_42 = new QLabel(tab_9);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(10, 10, 210, 30));
        label_42->setFont(font7);
        tabWidget->addTab(tab_9, QString());
        tab_10 = new QWidget();
        tab_10->setObjectName(QString::fromUtf8("tab_10"));
        label_9 = new QLabel(tab_10);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 10, 210, 30));
        label_9->setFont(font6);
        tabWidget->addTab(tab_10, QString());
        pushButton_2 = new QPushButton(centralwidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(510, 70, 471, 471));
        line_3 = new QFrame(centralwidget);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(980, 0, 21, 561));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        btnViewPlanet = new QPushButton(centralwidget);
        btnViewPlanet->setObjectName(QString::fromUtf8("btnViewPlanet"));
        btnViewPlanet->setGeometry(QRect(1000, 280, 122, 122));
        btnViewPlanet->setStyleSheet(QString::fromUtf8(""));
        btnViewDescription = new QPushButton(centralwidget);
        btnViewDescription->setObjectName(QString::fromUtf8("btnViewDescription"));
        btnViewDescription->setGeometry(QRect(1120, 280, 122, 122));
        btnViewDescription->setStyleSheet(QString::fromUtf8(""));
        btnViewSystem = new QPushButton(centralwidget);
        btnViewSystem->setObjectName(QString::fromUtf8("btnViewSystem"));
        btnViewSystem->setGeometry(QRect(1240, 280, 122, 122));
        btnViewSystem->setStyleSheet(QString::fromUtf8(""));
        btnViewMap = new QPushButton(centralwidget);
        btnViewMap->setObjectName(QString::fromUtf8("btnViewMap"));
        btnViewMap->setGeometry(QRect(1360, 280, 122, 122));
        btnViewMap->setStyleSheet(QString::fromUtf8(""));
        btnAutogen = new QPushButton(centralwidget);
        btnAutogen->setObjectName(QString::fromUtf8("btnAutogen"));
        btnAutogen->setGeometry(QRect(1000, 180, 240, 80));
        QFont font10;
        font10.setPointSize(18);
        btnAutogen->setFont(font10);
        btnAutogen->setStyleSheet(QString::fromUtf8(""));
        line = new QFrame(centralwidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(1000, 160, 481, 21));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralwidget);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(1000, 260, 481, 21));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        btnLogo = new QPushButton(centralwidget);
        btnLogo->setObjectName(QString::fromUtf8("btnLogo"));
        btnLogo->setGeometry(QRect(1166, 412, 150, 150));
        btnLogo->setIconSize(QSize(150, 150));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1500, 21));
        menubar->setStyleSheet(QString::fromUtf8(""));
        menu = new QMenu(menubar);
        menu->setObjectName(QString::fromUtf8("menu"));
        menu->setStyleSheet(QString::fromUtf8(""));
        menu_2 = new QMenu(menubar);
        menu_2->setObjectName(QString::fromUtf8("menu_2"));
        menuGenerationSettings = new QMenu(menu_2);
        menuGenerationSettings->setObjectName(QString::fromUtf8("menuGenerationSettings"));
        menuProgramSettings = new QMenu(menu_2);
        menuProgramSettings->setObjectName(QString::fromUtf8("menuProgramSettings"));
        menu_3 = new QMenu(menubar);
        menu_3->setObjectName(QString::fromUtf8("menu_3"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menu->menuAction());
        menubar->addAction(menu_2->menuAction());
        menubar->addAction(menu_3->menuAction());
        menu->addAction(action);
        menu->addAction(action_8);
        menu->addAction(action_2);
        menu->addAction(action_9);
        menu_2->addAction(menuGenerationSettings->menuAction());
        menu_2->addAction(menuProgramSettings->menuAction());
        menuGenerationSettings->addAction(action_3);
        menuGenerationSettings->addAction(action_4);
        menuGenerationSettings->addAction(action_5);
        menuProgramSettings->addAction(action_10);
        menuProgramSettings->addAction(action_live);
        menu_3->addAction(action_achievements);
        menu_3->addAction(action_6);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(5);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "God of pixels 3", nullptr));
        action->setText(QCoreApplication::translate("MainWindow", "Save image", nullptr));
        action_2->setText(QCoreApplication::translate("MainWindow", "Save planet", nullptr));
        action_3->setText(QCoreApplication::translate("MainWindow", "Save", nullptr));
        action_4->setText(QCoreApplication::translate("MainWindow", "Load", nullptr));
        action_5->setText(QCoreApplication::translate("MainWindow", "Load defaults", nullptr));
        action_6->setText(QCoreApplication::translate("MainWindow", "About program", nullptr));
        action_achievements->setText(QCoreApplication::translate("MainWindow", "Achievements", nullptr));
        action_7->setText(QCoreApplication::translate("MainWindow", "\320\237\320\276\320\274\320\276\321\211\321\214", nullptr));
        action_8->setText(QCoreApplication::translate("MainWindow", "Save full image", nullptr));
        action_9->setText(QCoreApplication::translate("MainWindow", "Load planet", nullptr));
        action_10->setText(QCoreApplication::translate("MainWindow", "Switch language", nullptr));
        action_live->setText(QCoreApplication::translate("MainWindow", "Quick update", nullptr));
        btnCreate->setText(QCoreApplication::translate("MainWindow", "Create", nullptr));
        btnRecreate->setText(QCoreApplication::translate("MainWindow", "Change", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Quality", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Amplitude", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Temperature", nullptr));
        pushButton_6->setText(QCoreApplication::translate("MainWindow", "t change", nullptr));
        pushButton_7->setText(QCoreApplication::translate("MainWindow", "img repo", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Main", nullptr));
        comboTerraMode->setItemText(0, QCoreApplication::translate("MainWindow", "noise", nullptr));
        comboTerraMode->setItemText(1, QCoreApplication::translate("MainWindow", "fault formation", nullptr));

        label_44->setText(QCoreApplication::translate("MainWindow", "Algorithm", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindow", "Detalisation", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QString());
        label_11->setText(QCoreApplication::translate("MainWindow", "Structure", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QString());
        label_8->setText(QCoreApplication::translate("MainWindow", "Biom", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "rocks", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "mountains", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "plains", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "lowlands", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "beaches", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "shelf", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "ocean", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "Color", nullptr));
        btnColorIce->setText(QString());
        btnColorRock->setText(QString());
        btnColorMountain->setText(QString());
        btnColorPlain->setText(QString());
        btnColorBeach->setText(QString());
        btnColorShallow->setText(QString());
        btnColorOcean->setText(QString());
        label_12->setText(QCoreApplication::translate("MainWindow", "Colors", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindow", "Noise", nullptr));
        checkGradient->setText(QCoreApplication::translate("MainWindow", "Gradient", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QString());
        checkPlant->setText(QCoreApplication::translate("MainWindow", "Plants", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "Life", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QString());
        label_13->setText(QCoreApplication::translate("MainWindow", "Lighting", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "Light", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QString());
        label_23->setText(QCoreApplication::translate("MainWindow", "Planet's name", nullptr));
        radioName1->setText(QCoreApplication::translate("MainWindow", "GoP2 standart", nullptr));
        radioName2->setText(QCoreApplication::translate("MainWindow", "human-friendly", nullptr));
        radioName3->setText(QCoreApplication::translate("MainWindow", "random", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindow", "Name", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QString());
        checkCloud->setText(QCoreApplication::translate("MainWindow", "Clouds", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "Size", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "Detalization", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "Transparent", nullptr));
        checkCorrection->setText(QCoreApplication::translate("MainWindow", "Correction", nullptr));
        btnColorCloud->setText(QCoreApplication::translate("MainWindow", "Color", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "Clouds", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_7), QString());
        checkAtmo->setText(QCoreApplication::translate("MainWindow", "Atmosphere", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "Transparent", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "Size", nullptr));
        btnColorAtmo->setText(QCoreApplication::translate("MainWindow", "Color", nullptr));
        label_43->setText(QCoreApplication::translate("MainWindow", "Atmosphere", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_8), QString());
        checkRing->setText(QCoreApplication::translate("MainWindow", "Rings", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "R internal", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "R external", nullptr));
        btnColorRing->setText(QCoreApplication::translate("MainWindow", "Color", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "Rings", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_9), QString());
        label_9->setText(QCoreApplication::translate("MainWindow", "North", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_10), QString());
        pushButton_2->setText(QString());
        btnViewPlanet->setText(QCoreApplication::translate("MainWindow", "Planet", nullptr));
        btnViewDescription->setText(QCoreApplication::translate("MainWindow", "Description", nullptr));
        btnViewSystem->setText(QCoreApplication::translate("MainWindow", "Tags", nullptr));
        btnViewMap->setText(QCoreApplication::translate("MainWindow", "Map", nullptr));
        btnAutogen->setText(QCoreApplication::translate("MainWindow", "Autogen", nullptr));
        btnLogo->setText(QString());
        menu->setTitle(QCoreApplication::translate("MainWindow", "File", nullptr));
        menu_2->setTitle(QCoreApplication::translate("MainWindow", "Settings", nullptr));
        menuGenerationSettings->setTitle(QCoreApplication::translate("MainWindow", "Generation settings", nullptr));
        menuProgramSettings->setTitle(QCoreApplication::translate("MainWindow", "Program settings", nullptr));
        menu_3->setTitle(QCoreApplication::translate("MainWindow", "Information", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
